version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672" # dashboard http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:80"
    depends_on:
      - rabbitmq

  notification-service:
    build: ./notification-service
    container_name: message-service
    depends_on:
      - rabbitmq

